export const GET_LOP_HOC = "GET_LOP_HOC";
export const GET_LOP_HOC_SUCCESS = "GET_LOP_HOC_SUCCESS";

export const SAVE_LOP_HOC = "SAVE_LOP_HOC";
export const SAVE_LOP_HOC_SUCCESS = "SAVE_LOP_HOC_SUCCESS";

export const SET_LOP_HOC_EDITING = "SET_LOP_HOC_EDITING";

export const DELETE_LOP_HOC = "DELETE_LOP_HOC";
export const DELETE_LOP_HOC_SUCCESS = "DELETE_LOP_HOC_SUCCESS";
