export const FETCH_NAM_HOC = "FETCH_NAM_HOC";
export const FETCH_NAM_HOC_SUCCESS = "FETCH_NAM_HOC_SUCCESS";

export const SAVE_NAM_HOC = "SAVE_NAM_HOC";
export const SAVE_NAM_HOC_SUCCESS = "SAVE_NAM_HOC_SUCCESS";

export const SET_NAM_HOC_EDITING = "SET_NAM_HOC_EDITING";

export const DELETE_NAM_HOC = "DELETE_NAM_HOC";
export const DELETE_NAM_HOC_SUCCESS = "DELETE_NAM_HOC_SUCCESS";
