export const GET_STUDENT_CLASS = "GET_STUDENT_CLASS";
export const GET_STUDENT_CLASS_SUC = "GET_STUDENT_CLASS_SUC";

export const SAVE_STUDENT_CLASS = "STUDENT_CLASS";
export const SAVE_STUDENT_CLASS_SUC = "SAVE_STUDENT_CLASS_SUC";
